[general]
PLANTOID=15
ENABLE_BLOCKCHAIN = "False"
ENABLE_ARDUINO = "True"
USE_GOERLI = "True"
USE_MAINNET = "False"
GOERLI_FAILSAFE=0
MAINNET_FAILSAFE=0
ELEVEN_VOICE_ID="o7lPjDgzlF8ZloHzVPeK" 
#21m00Tcm4TlvDq8ikWAM
TRIGGER_LINE=""
# SET YOUR CONVERSATION ROUNDS
max_rounds=5


[general.plantoid_14]
USE_GOERLI_ADDRESS = "0x9809D9C367fA49297c4b1F8E57A13a310b00cDc1"
USE_MAINNET_ADDRESS = "0xffe18b42de363a9b06b6a6a91733f50f998c3f13"
USE_METADATA_ADDRESS = "0x580fdc17a820e3c0d17fbcd1137483c5332fceb6"

[general.plantoid_15]
USE_GOERLI_ADDRESS = "0x0B60EE161d7b67fa231e9565dAFF65b34553bC6F"
USE_MAINNET_ADDRESS = "0x4073E38f71b2612580E9e381031B0c38B3B4C27E"
USE_METADATA_ADDRESS = "0x580fdc17a820e3c0d17fbcd1137483c5332fceb6"

[audio]
device_bias=-100
threshold_bias=0
