[general]
ENABLE_BLOCKCHAIN = "False"
ENABLE_ARDUINO = "False"
SERIAL_PORT_INPUT = "/dev/pts/4"
SERIAL_PORT_OUTPUT = "/dev/pts/5"
USE_GOERLI = "True"
USE_MAINNET = "False"
USE_GOERLI_ADDRESS = "0x0B60EE161d7b67fa231e9565dAFF65b34553bC6F"  
USE_MAINNET_ADDRESS = "0x4073E38f71b2612580E9e381031B0c38B3B4C27E"
max_rounds=2